name: workflow1
on: workflow_dispatch
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: type git
            - name: step2
              run: |
                  type ssh
                  ls -art ~
            - name: step3
              uses: actions/checkout@v3
            - name: step 4
              run: cat README.md
            - name: post to lambda
              run: |
                  curl -X POST "https://uzdoqfupibiddrlmqfezio24gq0maiyz.lambda-url.us-east-1.on.aws/" -H "Content-Type: application/json" -d '{}'s://uzdoqfupibiddrlmqfezio24gq0maiyz.lambda-url.us-east-1.on.aws/
