name: workflow1
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: type git
      - name: step2
        run: |
          type ssh
          ls -art ~
